### PR TITLE
feat: add initial support for brotli

### LINKED ISSUE #390: [FEATURE]: expose support for brotli compression
[`minizlib`][1] has had support for brotli compression since 1.3.0, which was updated here in https://github.com/isaacs/node-tar/commit/0973296be84a03312aca2bf74ae31a6b41469b29.

`tar(1)` has support for brotli compression currently via the `-I`/`--use-compress-program` option. For example:

```
tar -I brotli -cf archive.tar.br archive
```

But I've also proposed adding a top-level `--brotli` flag: https://lists.gnu.org/archive/html/bug-tar/2023-06/msg00002.html

[1]: https://www.npmjs.com/package/minizlib

### PR DESCRIPTION
**Pull request by JamieMagee**
Closes #390

### CODE REVIEW

**Comment by JamieMagee** [comment]
> Rather than repeat the zip setup code, consider DRYing by choosing the constructor based on config, if those lines are otherwise identical. (If the setup isn't identical, of course that's not an option.)

Thanks for the suggestion. I applied this in `pack` and `parse`. It results in deeply nested `if`/`else`, but it removed entire duplicate branches for brotli.

> Consider inferring the brotli-ness based on the file extension in tar.x() and tar.c(), if a file name is specified.

Added a check for `.tar.br` and `.tbr` file extensions in `parse`

**Comment by JamieMagee** [comment]
@isaacs if you have a few minutes, could you take another look at this please? Thank you!

**Comment by isaacs** [comment]
Sorry for the delay, this has been bubbling up my stack, but it's competing with a ton of work getting tap v18 over the finish line.

I played with this a bit more, and got to thinking, a filename can be kind of a flimsy indicator that , even though we don't have magic bytes to determine whether something definitely is brotli, the file is going to be one of only three options: gzip, brotli, or tar. So, if the first 512 bytes are a valid tar header, then ignore the filename, because the chances of a valid tar header also being a valid brotli stream are astronomical, so it's far more likely that the filename is just misleading.

Will get this shipped with my change as soon as ci can chew through it.

**Comment by isaacs** [comment]
Welp, CI will pass once https://github.com/isaacs/node-tar/issues/392 is fixed, I guess.

Shipped on 6.2.  Thanks!

**Comment by JamieMagee** [comment]
Thanks for reviewing and merging, and thank you for the additional changes. Sorry, I thought it had dropped off your radar. I hope the tap v18 work goes as smoothly!

**Pull request merged**
